name: "Build"
on:
  push:
    branches:
      - master
  schedule:
    # Random time each week.
    - cron:  '32 8 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: silvenga-docker/build-image@latest
      with:
        dockerUserName: silvenga-docker
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        dockerImageName: ${{ github.repository }}/deluge
        dockerTags: latest,${{ github.sha }}
